import {
  ACCESSORIES,
  BLANKET,
  BODY_WIDTH,
  BOX_ROWS,
  CROUCHED,
  CROWN,
  ENERGY_MARKS,
  FLAT,
  FLYING_CAP,
  GRID_ROWS,
  HEADS,
  LAPTOP,
  LEANING,
  LEGS,
  MINI,
  MINI_HEADS,
  MINI_LEGS,
  MINI_OVERLAYS,
  MINI_SAT,
  OVERLAYS,
  REACH,
  SLOT,
  SQUASHED,
  TORSOS,
} from './mascot-sprites'

// hooks/mascot-sprites.ts's frame tables, gathered for the tests.

/** Every table, by name, with the size each of its frames has: what the integrity test walks. */
export const FRAME_TABLES: readonly { name: string; width: number; height: number; frames: readonly (readonly string[])[] }[] = [
  { name: 'HEADS', width: BODY_WIDTH, height: 1, frames: Object.values(HEADS).map(row => [row]) },
  { name: 'TORSOS', width: BODY_WIDTH, height: 1, frames: Object.values(TORSOS).map(row => [row]) },
  { name: 'LEGS', width: BODY_WIDTH, height: 1, frames: Object.values(LEGS).map(row => [row]) },
  { name: 'SQUASHED', width: BODY_WIDTH, height: 2, frames: [SQUASHED] },
  { name: 'FLAT', width: BODY_WIDTH, height: 2, frames: [[FLAT.legs, FLAT.body]] },
  { name: 'CROUCHED', width: BODY_WIDTH, height: 1, frames: [[CROUCHED]] },
  { name: 'BLANKET', width: BODY_WIDTH, height: 2, frames: BLANKET.quilt.map(quilt => [quilt, BLANKET.hem]) },
  { name: 'ACCESSORIES', width: 3, height: 1, frames: [...Object.values(ACCESSORIES).map(one => [one.art]), [CROWN.art], [FLYING_CAP.art]] },
  { name: 'ACCESSORIES.mini', width: 2, height: 1, frames: Object.values(ACCESSORIES).map(one => [one.mini]) },
  { name: 'ENERGY_MARKS', width: 2, height: 1, frames: [...ENERGY_MARKS.right, ...ENERGY_MARKS.left].map(mark => [mark]) },
  { name: 'MINI_HEADS', width: MINI, height: 1, frames: Object.values(MINI_HEADS).map(row => [row]) },
  { name: 'MINI_LEGS', width: MINI, height: 1, frames: Object.values(MINI_LEGS).map(row => [row]) },
  { name: 'MINI_SAT', width: MINI, height: 1, frames: [[MINI_SAT]] },
  { name: 'LEANING', width: BODY_WIDTH, height: 1, frames: Object.values(LEANING).map(row => [row]) },
  ...Object.entries(OVERLAYS).map(([name, frames]) => ({ name: `OVERLAYS.${name}`, width: SLOT, height: GRID_ROWS, frames: frames.map(one => one.art) })),
  { name: 'LAPTOP', width: SLOT, height: GRID_ROWS, frames: LAPTOP.map(one => one.art) },
  { name: 'REACH', width: SLOT, height: GRID_ROWS, frames: [REACH] },
  ...Object.entries(MINI_OVERLAYS).map(([name, frames]) => ({ name: `MINI_OVERLAYS.${name}`, width: MINI, height: BOX_ROWS, frames: frames.map(one => one.art) })),
]
